### ISSUE TITLE
Java 8 support

### ISSUE THREAD

**Issue by albertotn** [xmlet/XsdParser#1]
Could you please make xmlet available for Java 8 too ? Thanks

**Comment by albertotn** [comment]
Thanks for the update!
I saw on maven repository (https://mvnrepository.com/artifact/com.github.xmlet/xsdParser) no artifact for version 1.0.10 and if I'm see correctly here https://github.com/xmlet/XsdParser/blob/master/pom.xml you released a 1.0.10-SNAPSHOT version right?

My 2 cents: on release, make a tag, so on release tab here on github is clear you have done a new release

I plan to use you library, do you have some kind of roadmap or list of known issues?

**Comment by lcduarte** [comment]
I don't know why the artifact doesn't show on that site, I usually check on the maven central repository 
(https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22xsdParser%22) and the artifact is there. As for the information on the repository it was my fault, forgot to push my changes after performing the release, this is the POM of the release https://github.com/xmlet/XsdParser/blob/xsdParser-1.0.10/pom.xml.

As for the library, it suits my needs and I think it covers most of the issues of XSD parsing, the only thing I still plan on doing is adding more verifications to ensure that the file being parsed follows most of the XSD language specifications. You can try it out and if you find it lacks some elements you need or find any bug I'll try to solve it ASAP.
