### ISSUE TITLE
documentation.getContent()

### ISSUE THREAD

**Issue by Tim-W** [xmlet/XsdParser#10]
Hi, I am not sure if this is a bug or if this is supposed to be cleaned out when parsing the XSD.

When calling element.getAnnotation().getDocumentations(), and the documentations are defined as follows:

```
	<xs:element name="someElement">
		<xs:annotation>
			<xs:documentation><![CDATA[
			CDATA line 1
			CDATA line 2
			]]></xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[0-9]{9}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
```
Then each documentation.getContent() call returns an empty string. Is this a bug in the code or should I try to find a workaround for my perhaps too specific usecase?

**Comment by lcduarte** [comment]
Hello Tim, 

Thanks for your issue. The problem in your case was that the contents of the documentation tag weren't exactly a text node, but a CDATA node, which I wasn't taking in consideration.

A new release was performed,[1.0.20](https://github.com/xmlet/XsdParser/tree/xsdParser-1.0.20), and now you have the CDATA contents in the documentation.getContent() call.

Check that out and if it's all cool close this issue :)

**Comment by Tim-W** [comment]
Thank you :+1:
