### ISSUE TITLE
Exception handling during parsing

### ISSUE THREAD

**Issue by Dahausa** [xmlet/XsdParser#12]
Hi,

first of all, thanks for this library. :) 
I haven't found any other doing the same thing you do with your library.
I'm considering to use it in an application.
 
But one thing that prevents me from using it is the fact how exceptions are handled.

Every exception during parsing is caught inside the try/catch.
So a client using the library doen't know that something went wrong. :-(
 
In my opinion it'll be helpfull to propagate any exception as a runtime exception to clients in order that the client is able to react on that exception.

What I propose is...

to change this:
```java
} catch (SAXException | IOException | ParserConfigurationException e) {
     Logger.getAnonymousLogger().log(Level.SEVERE, "Exception while parsing.", e);
}
```

into this:

```java
} catch (SAXException | IOException | ParserConfigurationException e) {
     Logger.getAnonymousLogger().log(Level.SEVERE, "Exception while parsing.", e);
      throw new RuntimeException(e);
}
```
What do you think?
Shall I submit a pull request to change this?

**Comment by lcduarte** [comment]
Hi,

Thanks for using it! :)

Sure, I can make that change. I'll try to perform a new release today or maybe tomorrow if I can.

**Comment by lcduarte** [comment]
I performed a new release, [1.0.22](https://github.com/xmlet/XsdParser/tree/xsdParser-1.0.22). If you notice anything else feel free to open another issue :)

**Comment by Dahausa** [comment]
That was fast! Thanks :)

**Comment by fmcarvalho** [comment]
@Dahausa I noticed that you are not a XsdParser stargazer yet. Could you please give a star to increase popularity.  Thanks

**Comment by Dahausa** [comment]
Sure! You got a new star :)
