### ISSUE TITLE
Namespaces without "http://" do not parse

### ISSUE THREAD

**Issue by aniskop** [xmlet/XsdParser#18]
Hi,
I use xsdParser-1.0.24. Found an issue with namespaces -- XSD parsing fails, when namespace does not start with "http://".
Use case for such namespaces is ISO20022 where `xmlns` is kind of `xmlns="urn:iso:std:iso:20022:tech:xsd:camt.053.001.08"`. You can look [at ISO20022 site](https://www.iso20022.org/full_catalogue.page), [camt.053 schema](https://www.iso20022.org/sites/default/files/documents/messages/camt/schemas/camt.053.001.08.zip) for instance).
So this sample XSD parses OK.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Document" type="xs:string"/>
    <xs:simpleType name="AMLIndicator">
        <xs:restriction base="xs:boolean"/>
    </xs:simpleType>
</xs:schema>
```
But when I add `xmlns="abc"`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="abc">
    <xs:element name="Document" type="xs:string"/>
    <xs:simpleType name="AMLIndicator">
        <xs:restriction base="xs:boolean"/>
    </xs:simpleType>
</xs:schema>
```
Parsing fails with the following error:
```
org.xmlet.xsdparser.xsdelements.exceptions.ParsingException: XsdSchema refers a namespace which was not imported.
```
Then I add "http://" and it parses well (with 0 unresolved elements):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://abc">
    <xs:element name="Document" type="xs:string"/>
    <xs:simpleType name="AMLIndicator">
        <xs:restriction base="xs:boolean"/>
    </xs:simpleType>
</xs:schema>
```

**Comment by lcduarte** [comment]
Hello,

First, thanks for using this library!

The library doesn't validate xml namespaces that aren't present locally, as in, present in the file system. So in order to decide if I should search locally for a namespace definition to import and validate I check if the xmlns starts with http and actively ignore those since they aren't local. 

In the ```abc``` example the library searches for a xsd import tag with the namespace attribute with the value ```abc```, and since it doesn't find it you get a parsing exception.

Hope this explanation helps.

**Comment by radboudp** [comment]
Hi there,
I have a similar problem. But first: I like the library. It has a lot of potential for us. However, the XSD we like to parse has some elements inside documentation blocks which the library tries to parse, and there is no import for them. The namespace ccts is defined like this:

`xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"`

So we get an "XsdSchema refers a namespace which was not imported." error when we parse our XSD. The XSD file itself is external and I could add an import for the namespace, but it seems to be elusive... What do you suggest? Any way to handle this?


`<xsd:complexType name='FooType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>123</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry><value>01</value><definition>Male</definition></CodeListEntry>
					<CodeListEntry><value>02</value><definition>Female</definition></CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='1'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(01|02){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>`

**Comment by aniskop** [comment]
@lcduarte, thanks for the explanation. Sounds very reasonable. I'll take my time to think a little bit about it :) That's the reason I don't close the issue. I'll do it when I'm done thinking :)
I also want to refresh my knowledge on `xmlns` and `targetNamespace` -- what they mean and what is their purpose. As far as I know, XML Schema also defines own namespace, which in turn can be used in other schemas or XML documents, so I'm in doubt a little bit about your arguments.
@radboudp , for now I see the only solution -- remove namespace without http:// before processing, which possibly is not easy. I did not try that, but I'll definitely will.

**Comment by radboudp** [comment]
I solved it for now by defining an empty xsd and importing it for the namespace.

**Comment by aniskop** [comment]
@lcduarte ,
I'm closing the issue, but I'm still not convinced about `targetNamespace`. As I understand, it defines a namespace (e.g. container) for the element names defined by the XSD. For this reason `targetNamespace` should not be validated. But if the name, defined by this `targetNamespace` is used in another XSD, then yes &ndash; validation can/must be performed, but in such case validation will be performed on `xmlns`.
