### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by radboudp** [xmlet/XsdParser#20]
Hi,

We have the following XSD:

`
    <xsd:complexType name="fooType">
        <xsd:sequence>
            <xsd:element name="id" type="FooIDType"/>
        </xsd:sequence>
    </xsd:complexType>
`
`
    <xsd:simpleType name="FooIDType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="(XX|YY|ZZ):[a-zA-Z0-9]{4,10}"/>
        </xsd:restriction>
    </xsd:simpleType>
`

When I call getXsdComplexType() on the XsdElement for "id" in the fooType, then we encounter an ClassCastException because the underlaying type is a XsdSimpleType. I had expected the getXsdComplexType() method to return null.

`
java.lang.ClassCastException: org.xmlet.xsdparser.xsdelements.XsdSimpleType cannot be cast to org.xmlet.xsdparser.xsdelements.XsdComplexType
	at org.xmlet.xsdparser.xsdelements.XsdElement.getXsdType(XsdElement.java:297)
	at org.xmlet.xsdparser.xsdelements.XsdElement.getXsdComplexType(XsdElement.java:288)
	at nl.svb.sem.correspondentiemanager.xsd.model.XsdStructure.findComplexForElement(XsdStructure.java:76)
`

**Comment by lcduarte** [comment]
Hello, 

Thanks for reporting the issue, it was indeed an oversight on my part. 

I performed a new release to fix it, [1.0.25](https://github.com/xmlet/XsdParser/tree/xsdParser-1.0.25). If you notice anything else feel free to open another issue :)

**Comment by radboudp** [comment]
My pleasure. Thank you for picking it up so quickly. 👍
