### ISSUE TITLE
xsd:double parsed as ComplexType

### ISSUE THREAD

**Issue by radboudp** [xmlet/XsdParser#21]
`			<xsd:element name = 'hoursPerWeek' minOccurs='0' maxOccurs='1' type='xsd:double'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>F8C43CF9-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>`

Above xsd:double inside a sequence inside a global named complexType is identified as an complexType.

![image](https://user-images.githubusercontent.com/16594760/74043608-fe2f7a80-49c9-11ea-8909-16887e82ea00.png)

**Comment by lcduarte** [comment]
Hi,

This is the default behaviour for types of XSD that have representation in the Java language. This list is defined in [getXsdTypesToJava of ParserConfig](https://github.com/xmlet/XsdParser/blob/master/src/main/java/org/xmlet/xsdparser/core/utils/DefaultParserConfig.java). This means that if any element has an attribute ```type``` with one of the values defined in this method a XsdComplexType will be created to represent the respective xsd type.

This aims to stardardize the way the ```type``` attribute usually refers to another ```xsd:complexType``` or ```xsd:simpleType```.

If you want to access the value of the ```type``` attribute you can always use:

```java
currentElement.getAttributesMap().get("type");
//Or as of 1.0.25
currentElement.getAttributesMap().get(XsdAbstractElement.TYPE_TAG); 
```

Hope this helped!

**Comment by radboudp** [comment]
I find this counter intuitive in respect to when the a type attribute refers to an actual complextype or an actual simple type. Actually a type that refers to an xsd base type might require a class if itself. 

It is most definitely not a complextype.

**Comment by lcduarte** [comment]
I get your point. I added another type ```XsdBuiltInDataType``` to represent the built in Xsd types, which can be configured in the configuration of the parser if for some reason the default configuration is missing something you need.

It still works the same way if the type attribute refers a ```xsd:complexType``` or a ```xsd:simpleType``` element but if it refers a type configured as a built in xsd type it maps it to a ```XsdBuiltInDataType``` instance.

There are also four new methods in XsdElement to reflect this change:

```java
public XsdNamedElements getTypeAsXsd();
public XsdComplexType getTypeAsComplexType();
public XsdSimpleType getTypeAsSimpleType();
public XsdBuiltInDataType getTypeAsBuiltInDataType();
```

The new release is published with these changes - [1.0.27](https://github.com/xmlet/XsdParser/tree/xsdParser-1.0.27).

**Comment by radboudp** [comment]
Hi Luis,

Many thanks, What prompted you to create this library?

Let me explain to what we are doing. We have created a generic forms backend for outgoing correspondence. It provides logic like multiple versions of the correspondence filled out, allowing users to save draft en final versions, rollback, continue old versions, commit, release for sending. The correspondence is filled out with data collected in a form. This data and form are generic and is managed by an XSD. So a correspondence received by this backend is accompanied by a type, which is linked to an XSD. The XSD is used to translate de JSON data (no ordering required) to XML, respecting the ordering of the XSD. Also we validate the form data against the XSD. We noticed that regular validation lacks in reporting a number of problems. For example, it reports for instance an error "unexpected field" in stead of errors on missing required fields.

Your library comes in to analyse the XSD and extract information about each allowed item in the XSD. We put all that information in a map, with the XPATH to the element as key for easy, quick access. We collect the following information per element:

- is it a simple type?
- is it a complex type?
- if it is simple, is it nummeric, boolean, binary or other? 
- What are the allowed sub elements? (in order as in the XSD).
- What are the required sub elements?
- Which sets of choice elements are present?

We could have collected the information directly parsing the XSD DOM strucure, but your library made it a lot easier! Many thanks!

Currently we use underscore library to translate the JSON to XML. For XML to JSON we use SAX2J library found on github. I am thinking about using your library to build our own JSON to XML and XML to JSON library with knowledge of the XSD. Problem at converting JSON to XML and vice versa is knowing if something should be an array in JSON (thus allowed multiple times). From analyzing the XML alone, you can only see this when an element is present multiple times. Therefor the underscore library adds all sorts of attributes to the XML, preventing a validation against the XSD, but allowing reverse conversion. When the XSD allowed into the conversion, then these attributes are not necessary.

Keep up the good work on your library!

**Comment by lcduarte** [comment]
Thanks for the message, it's always nice to know how our code is helping other people!

This library started as a means to an end. In my master thesis I needed to convert a XSD definition into a fluent Java API. In order to do that I needed a tool to properly map the whole XSD language to Java so I could extract all the required information about the XSD definition in order to create an API that best reflects the XSD that was being used. 

The use case was the HTML language, with the respective XSD definition. That ultimately resulted in the [HtmlFlow library](https://github.com/xmlet/HtmlFlow) which uses the [HtmlApiFaster API](https://github.com/xmlet/HtmlApiFaster) which was generated based on the information extracted by this library. 

In that context this library has stagnated since it already does what was required, but I still mantain it to help other developers use it in order to solve their problems.

Feel free to keep posting issues, I may not respond during the week but usually on the weekends I'll check it out.

**Comment by fmcarvalho** [comment]
@radboudp We are always curious about applications of our libraries and I found very interesting your use case and the use of XSD. Can you explain a little bit more about the XML need? What is the end goal of having data in XML format?

Thank you,
Miguel

**Comment by radboudp** [comment]
We have to connect to a system exchanging large numbers of data in XML with many different types of messages, that also uses multiple versions of these messages, since there are over 14000 parties using them.
    On Monday, February 10, 2020, 11:58:41 AM GMT+1, Fernando Miguel Gamboa de Carvalho <notifications@github.com> wrote:  
 
 
@radboudp We are always curious about applications of our libraries and I found very interesting your use case and the use of XSD. Can you explain a little bit more about the XML need? What is the end goal of having data in XML format?

Thank you,
Miguel

**Comment by fmcarvalho** [comment]
@radboudp Can you send me an email to talk a little bit more about that system privately?
