### ISSUE TITLE
Add support for XSD-files inside jars.

### ISSUE THREAD

**Issue by hareve** [xmlet/XsdParser#3]
Today it is not possible to parse XSDs inside jars (you get "FIleNotFoundException").

The check for File.exists() in XsdParser.parseFile() could be change to:
            if (!(filePath.startsWith("jar:") || filePath.startsWith("file:")) && !new File(filePath).exists()){
                throw new FileNotFoundException();
            }

Then you could use: new XsdParser(RandomClass.class.getResource(filename).toExternalForm()) to use an XSD-file bundled inside a JAR-file (optionally it could have a constructor with an InputStream).

**Comment by lcduarte** [comment]
The new version, 1.0.14, is released now.

**Comment by fmcarvalho** [comment]
@hareve can you check please if the last release 1.0.14  solves your issue?

And can you give a star to this repository?

Thanks
