### ISSUE TITLE
Problems using XsdParser in Windows

### ISSUE THREAD

**Issue by cesarzea** [xmlet/XsdParser#36]
I ma having problems parsing the XSD in windows. There are a lot of missing attributes: 

In MacOs: 

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/34435748/143494947-c798b307-2bb2-4d2b-9cb5-a19caa36888d.png">

In Windows with the same code, same input XSD, and same JDK version, at same code line:

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/34435748/143495062-23badb5f-d01c-4dab-878f-a958479a90ff.png">

I don't know how to investigate the problem. 

Thanks a lot.

**Comment by lcduarte** [comment]
Hello, can you provide me the XML that you are having issues parsing in Windows so I can test it?

**Comment by cesarzea** [comment]
There are a problem with the paths that contains the separator "\\"

This works perfectly on both mac and windows:
```
 this.parserInstance = new XsdParser("libs/metadata_lib.xsd");
```

But this has the commented problem: 
```
 this.parserInstance = new XsdParser("libs\\metadata_lib.xsd");
```

This solve my problem, but I think perhaps there are a problem in the library. Thanks a lot for all your time and this library. It's amazing.

**Comment by lcduarte** [comment]
Thanks for the investigation, I'll try to investigate it further on future releases of the library to make it work in both MacOs and Windows.
