### ISSUE TITLE
Unable to get access from maven for version 1.2.2

### ISSUE THREAD

**Issue by MatapangMandirigma** [xmlet/XsdParser#42]
Just unable to get access to version 1.2.2 with maven.

pom.xml file has 
\<dependency>
    	\<groupId>com.github.xmlet\</groupId>
    	\<artifactId>xsdParser\</artifactId>
    	\<version>1.2.2\</version>
 \</dependency>
in it and the maven project returns an error. However it is able to the find version 1.2.1

**Comment by lcduarte** [comment]
Hello,

That's a weird issue, I've never had that kind of problem. Can you try again? I've checked and the artifact is available in the maven repository:

https://mvnrepository.com/artifact/com.github.xmlet/xsdParser
