### ISSUE TITLE
XML Schema causes XsdParser to exit with NullPointerException when calling isRelativePath()

### ISSUE THREAD

**Issue by d-gregorczyk** [xmlet/XsdParser#43]
### Description

When parsing a specific, quite complex XML Schema (see attachment), a `NullPointerException` is raised:

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.matches(String)" because "filePath" is null
	at org.xmlet.xsdparser.core.XsdParserCore.isRelativePath(XsdParserCore.java:492)
	at org.xmlet.xsdparser.core.XsdParserCore.lambda$resolveOtherNamespaceRefs$8(XsdParserCore.java:148)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1008)
	at org.xmlet.xsdparser.core.XsdParserCore.resolveOtherNamespaceRefs(XsdParserCore.java:109)
	at org.xmlet.xsdparser.core.XsdParserCore.resolveRefs(XsdParserCore.java:93)
	at org.xmlet.xsdparser.core.XsdParser.parse(XsdParser.java:66)
	at org.xmlet.xsdparser.core.XsdParser.<init>(XsdParser.java:38)
```

It looks like XsdParser performs a `isRelativePath()` on a null value because of a previous variable (`unsolvedElementSchema`) being null (see `XsdParserCore` on line 139). Debugging the code led me to XsdAbstractElement.java:

```
    public XsdSchema getXsdSchema(){
        XsdSchema schema = null;

        try {
            schema = getXsdSchema(this, new ArrayList<>());
        }
         catch (ParentAvailableException e){
            return null; ////////////// this one ultimately causes the parsing process to crash
         }

        if (schema == null){
            throw new ParsingException("The parent is null while searching for the XsdSchema. Please submit an issue with the xsd file being parsed to the project page.");
        }

        return schema;
    }
```

I tried to find a fix myself but wasn't able to entirely comprehend the code so far. Your help is very much appreciated!

### Expected behavior

The files have been tested as valid (XML Spy) and could be read in with a former version of XsdParser, which was 1.0.28.

### Library Version

1.2.0

### Additional context
The XML Schema that fails to parse is BICEPS_MessageModel.xsd.
[BICEPS_MessageModel.zip](https://github.com/xmlet/XsdParser/files/9127492/BICEPS_MessageModel.zip)

**Comment by lcduarte** [comment]
Hello, thanks for using the library!

Do you mind testing with the latest version, 1.2.2? I've tried to test it with the latest version and it looks ok, it might have been something solved either in 1.2.1 or 1.2.2.

Let me know if it works.

![imagem](https://user-images.githubusercontent.com/5586583/179400353-2a240b84-e49b-4460-8e4f-7b0a78d4b29b.png)

**Comment by d-gregorczyk** [comment]
Thanks for investigating so quickly! Actually, version 1.2.2 parses the document, but now I got stuck at another point.

I try to get the parent of an `XsdElement`, which in my case is an `XsdSchema`. However, `getParent()` returns null. I debugged and found out that there is the following code in `XsdAbstractElement`:

```
    public XsdAbstractElement getParent(boolean enforceParentAvailability) {
        if (!this.parentAvailable){
            if (enforceParentAvailability){
                throw new ParentAvailableException("The parent of this element isn't available to avoid circular memory dependencies.");
            }
            else {
                return null;
            }
        }

        return parent;
    }
```
Here, `enforceParentAvailability` is false and continues by returning null - even though parent != null. Is that on purpose?

In my code I need to obtain `elementFormDefault` from the parent `XsdSchema`. Since `XsdElement.getParent()` returns null, I am not able to access the data.

**Comment by lcduarte** [comment]
Hello,

I'm having some trouble replicating what you've identified. Using the code available in the IssuesTest, testIssue43 I have the following result:

![imagem](https://user-images.githubusercontent.com/5586583/180599754-6c61f9f2-2864-4acd-bb9b-b3ef5f7948a4.png)

The parser returns 55 elements, in which none have the getParent returning null.

You'll need to provide some additional details.

**Comment by d-gregorczyk** [comment]
Hi,

this looks a little bit more tricky, and perhaps I'm justing using the API incorrectly.

Take a look at this fancy `ParentNullTest.xsd` schema:

```xml
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:test="http://test" targetNamespace="http://test" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ReferencedElement">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Foo" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ReferencingElement">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="test:ReferencedElement" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
```

When trying to access `<xs:element ref="test:ReferencedElement" minOccurs="0"/>`, the `parent` member is not null, but the `parentAvailable` member is false, which is why `getParent()` returns null und my app crashes.

Some Kotlin test code to reproduce the error:

```kotlin
val p = XsdParser("ParentNullTest.xsd")
p.resultXsdSchemas.findFirst().get().let { schema ->
    val referencingElement = schema.xsdElements.asSequence()
        .filterNotNull()
        .filterIsInstance(XsdElement::class.java)
        .filter { it.name == "ReferencingElement" }
        .map { element: XsdAbstractElement? -> element as XsdElement? }
        .first() as XsdElement
    val referencedElement = referencingElement.xsdComplexType.xsdChildElement.xsdElements.asSequence().first() as XsdElement
    check(referencedElement.name == "ReferencedElement") // pass
    checkNotNull(referencedElement.xsdSchema) // fails
}
```

Is my assumption wrong that the element in the sequence should have an XsdSchema? And if yes, is it by any means possible to access the element `ReferencingElement` from within `ReferencedElement`?

Thanks again for your time to investigate this!

**Comment by lcduarte** [comment]
Hello,

I got the same issue as you! I think this is related with an issue I had 2 years ago when I fixed cloning elements to replace references.

In order to solve this:
```xml
<xs:element ref="test:ReferencedElement" minOccurs="0"/>
```

I clone the whole referenced element:

```xml
<xs:element name="ReferencedElement">
    <xs:complexType>
        <xs:sequence>
	    <xs:element name="Foo" type="xs:string"/>
	</xs:sequence>
    </xs:complexType>
</xs:element>
```

The issue is, in the original element 'ReferencedElement' the "parenthood" is well defined:

Foos A parent is Sequence A, Sequence A parent is ComplexType A, ComplexType A parent is Element A, Element A parent is XsdSchema.

But to keep the "parenthood" well defined in the cloned 'ReferencedElement' I had to clone all the contained elements:

```xml
<xs:complexType>
    <xs:sequence>
        <xs:element name="Foo" type="xs:string"/>
    </xs:sequence>
</xs:complexType>
```

This means that Object A keeps the same parents, but clone B has the following parent "tree":

Foos B parent is Sequence B, Sequence B parent is ComplexType B, ComplexType B parent is Element B, Element B parent is **XsdSequence from the ReferencingElement**.

In this example is pretty simple, it's just 3 elements, but I had issues with some people xsd files which had vast hierarchies and sometimes circular dependencies which resulted in the XsdParser to create GBs of objects in memory just to keep the "parenthood" right.

Even now, you may have the parent field with a value, but the value doesn't make sense, that's why the null is returned.

This is indeed a limitation of the library that I don't intend to fix in the foreseeable future, I'm sorry that I couldn't help more. I hope you find a way around this limitation.

**Comment by d-gregorczyk** [comment]
Oh that's too bad. :-( Thank you anyway! I guess we can work around that issue...
