### ISSUE TITLE
compatibility break in xsdRestriction version 1.2.4

### ISSUE THREAD

**Issue by vortex314** [xmlet/XsdParser#46]
getSimpleType on xsdRestriction suddenly fails after upgrade to latest version
```
  def simpleToType(xsdSimpleType: XsdSimpleType): String = {
    val base = xsdSimpleType.getRestriction.getBase
    if (base.startsWith("xs:")) base
    else {
      log.info("simpleType : " + xsdSimpleType.getName + " based on : " + xsdSimpleType.getRestriction.getSimpleType.getName)
      simpleToType(xsdSimpleType.getRestriction.getSimpleType)
    }
  }
```

**Comment by vortex314** [comment]
Downgrade to version 1.2.3 resolves the issue.
Compiler message with 1.2.4
value getSimpleType is not a member of org.xmlet.xsdparser.xsdelements.XsdRestriction

**Comment by lcduarte** [comment]
Hello,

The ```XsdRestriction``` class was changed to support both SimpleTypes and ComplexTypes with the 1.2.4 release. To get the same behavior of the old ```getSimpleType``` you should use ```getBaseAsSimpleType```.

If you get any other issue let me know.

**Comment by vortex314** [comment]
Thanks for the swift feedback, I've adapted my code accordingly
