### ISSUE TITLE
Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD

### ISSUE THREAD

**Issue by wolfomat** [xmlet/XsdParser#48]
Hi there, i am pretty new to this XSD Parsing stuff,

when I try to parse my XSD File, the Parser (or the underlaying framework) throws this error:

`org.xmlet.xsdparser.xsdelements.exceptions.ParsingException: Nicht unterstützt: http://javax.xml.XMLConstants/property/accessExternalDTD`

However, i've come across the "ParserConfig" - is there a chance/possibilty to make this work with this one?

And: Is there a more detailed documentation ?
Thanks!

**Comment by lcduarte** [comment]
Hello,

It might be related with some of the parameters or lack of them in this method:

[XsdParserCore.getDocumentBuilder()](https://github.com/xmlet/XsdParser/blob/master/src/main/java/org/xmlet/xsdparser/core/XsdParserCore.java#L517)

For a better response you would have to provide me with a small xsd file which generates that error.
