### ISSUE TITLE
Multiple Pattern are not supported

### ISSUE THREAD

**Issue by darthweiter** [xmlet/XsdParser#51]
**Describe the bug**
If a tag has multiple patterns, only the last pattern is used.

**Expected behavior**
The restriction has all patterns included.

**Library Version**
1.2.4

**Additional context**
Multiple pattern are a part of the schema: https://www.w3.org/TR/xmlschema-2/#src-multiple-patterns
[SDMXCommon_xsd.txt](https://github.com/xmlet/XsdParser/files/14230472/SDMXCommon_xsd.txt)

And it's a nice lib :)

**Comment by lcduarte** [comment]
Hello, thanks for using the library! I'm on vacations at the moment, I'll check this later this week.

**Comment by darthweiter** [comment]
Have a nice vacation!, i opened a new pr you can check later. And don't worry it's not so important.

**Comment by lcduarte** [comment]
Thanks!

I've approved your PR and released version [1.2.5](https://github.com/xmlet/XsdParser/tree/xsdParser-1.2.5) with the fix. Thanks for your contribution!
