### ISSUE TITLE
feature request: union with memberTypes are resolved

### ISSUE THREAD

**Issue by darthweiter** [xmlet/XsdParser#55]
An union element can have the attribute memberTypes, which indicates the members of the union. They aren't resolved right now. Only the simple types as child of an union are considered.

**Comment by lcduarte** [comment]
At first glance it looks good, I'll check it better later this week, I'll probably release it by the weekend or sooner if I'm able.

**Comment by lcduarte** [comment]
I've accepted the PR, I've made just some adjustments to the get method so that it returns a clone of the found element, to keep the same behaviour as the other methods that solve references.

**Comment by lcduarte** [comment]
I've released a new version, [1.2.8](https://github.com/xmlet/XsdParser/tree/xsdParser-1.2.8), with the code for this issue.
