### ISSUE TITLE
Modification not backward compatible in XsdRestriction (xsdParser 1.2.5+)

### ISSUE THREAD

**Issue by mttfranci** [xmlet/XsdParser#57]
First of all, I would like to thank you for providing this very usuful xsd parser.

**Describe the bug**
Upgrading xsdParser version from 1.2.4 to 1.2.6, the return type of method getPattern() has been changed. (from single value to list).
Here is the commit introducing the breaking change : 
https://github.com/xmlet/XsdParser/commit/859d8979f7553422ab4be3fc4e224b4e95962b62
This broke my software's build.

**Expected behavior**
Creating new method for new return type, flag the old one as deprecated and wait some time before removal.
Maybe using some sort of convention for breaking changes, for instance as in 
[semantic versioning](https://semver.org/)
(Changing the major version when a new release is not backward compatible)

**Library Version**
Upgrading from 1.2.4 to 1.2.6

**Additional context**
Here is a sample of the code that broke : 
[AutodocAttribute line 95](https://github.com/fugerit-org/fj-doc/blob/v3.4.1/fj-doc-lib-autodoc/src/main/java/org/fugerit/java/doc/lib/autodoc/parser/model/AutodocAttribute.java)

Thanks again!

**Comment by lcduarte** [comment]
Hello,

Thanks for using the library! Yeah, you are right, I've accepted the PR and didn't think about backwards compatibility. I've released a new version, [1.2.7](https://github.com/xmlet/XsdParser/tree/xsdParser-1.2.7), with the old method as it was before the change and a new method getPatterns, so everyone should be happy :)

**Comment by SimonCockx** [comment]
@lcduarte One more thing: could the old method be deprecated? I think it's a good change, but right now library users will only see this change "by coincidence". Adding a deprecated warning will make them aware of the good work being done here. :)

**Comment by lcduarte** [comment]
@SimonCockx I think the current solution is valid, both options are valid to be used, if the someone needs the list he'll look if another method is available.
