### ISSUE TITLE
[1.2.12] XsdSimpleType : NullPointerException on XsdParserCore.getXsdTypeToJava(unionMemberRestriction.getBase())

### ISSUE THREAD

**Issue by fugerit79** [xmlet/XsdParser#67]
**Describe the bug**

Thanks as always for the great work on keeping this library up to date and addressing users' issues.

Unfortunately, after upgrading to version 1.2.12 I get the error : 

java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "type" is null

	at org.xmlet.xsdparser.core.XsdParserCore.getXsdTypeToJava(XsdParserCore.java:680)
	at org.xmlet.xsdparser.xsdelements.XsdSimpleType.lambda$getAllRestrictions$1(XsdSimpleType.java:174)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.xmlet.xsdparser.xsdelements.XsdSimpleType.getAllRestrictions(XsdSimpleType.java:170)

**Expected behavior**
This seems to be a regresion, I would like to restore the version 1.2.11 behaviour

**Library Version**
1.2.12

**Additional context**
```xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
Sample test xsd for issue : https://github.com/xmlet/XsdParser/issues/67
xsd parser version 1.2.12
-->
<xsd:schema xmlns='http://www.w3.org/2000/10/XMLSchema'
	targetNamespace='https://github.com/xmlet/XsdParser/issues/67'
	xmlns:doc='https://github.com/xmlet/XsdParser/issues/67' xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name='info' type="doc:formatType">
	</xsd:element> 

	<xsd:simpleType name="formatType">
		<xsd:annotation>
			<xsd:documentation>Data format</xsd:documentation>
		</xsd:annotation>
		<xsd:union memberTypes="doc:formatDateType">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:minLength value="1"/>
					<xsd:maxLength value="128"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:union>
	</xsd:simpleType>

	<xsd:simpleType name="formatDateType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="yyyy-MM-dd"></xsd:enumeration>
			<xsd:enumeration value="yyyy-MM-dd hh:mm:ss"></xsd:enumeration>
			<xsd:enumeration value="yyyy-MM-dd'T'HH:mm:ss.SSSZ"></xsd:enumeration>
			<xsd:enumeration value="iso"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>
```

Test code : 

```java
    @Test
    public void testIssue67() {
        XsdParser xsdParser = new XsdParser( getFilePath("issue_67/a.xsd"));
        List<XsdElement> elements = xsdParser.getResultXsdElements().collect(Collectors.toList());
        for (XsdElement currentElement : elements) {
            XsdSimpleType simpleType = currentElement.getXsdSimpleType();
            if ( simpleType != null ) {
                 Assert.assertEquals( 2, simpleType.getAllRestrictions().size() );
            }
        }
    }
```

**Comment by lcduarte** [comment]
Hello, 

Thanks for identifying the issue and the PR, none of the tests covered that unfortunately. I've included null checks in the new methods that I've created for 1.2.12, it should fix the overall issue. I've released [1.2.13](https://github.com/xmlet/XsdParser/tree/xsdParser-1.2.13).
