### ISSUE TITLE
Using xs:include with relative paths leads to unresolved references

### ISSUE THREAD

**Issue by hschildb** [xmlet/XsdParser#69]
**Describe the bug**

Imagine the following directory layout (see [Home.zip](https://github.com/xmlet/XsdParser/files/15129683/Home.zip))

```
<Home>
	Sample.xml
	Main.xsd
	Include.xsd
	<A>
		Main.xsd
	<B>
		Include.xsd
```

If you like to use a type from `B/Include.xsd` in `A/Main.xsd` and, therefore, let  `A/Main.xsd` include `B/Include.xsd`, XsdParser does not resolve the type ref.

If both files are in the same directory (`Main.xsd` includes `Include.xsd`) no unresolved references occur.

It seems that if xs:include uses relative paths XsdParser fails to replace unresolved references.

In case you start the testing class from within the `<Home>` directory

```
import org.xmlet.xsdparser.core.XsdParser;

public class IncludeIssue
{
    public static void main(String... args) {
        
        XsdParser parser = new XsdParser( args[0] );
        
        parser.getUnsolvedReferences().stream().forEachOrdered(
            item -> System.out.println(
                String.format(
                    "Unresolved Ref: %s / Is Type Ref: %s",
                    item.getUnsolvedReference().getRef(),
                    item.getUnsolvedReference().isTypeRef()
                )
            )
        );
    }
}

```
	java IncludeIssue A/Main.xsd 

it outputs 

	Unresolved Ref: TypeA / Is Type Ref: true

However, there is no output if you use

	java IncludeIssue Main.xsd
	
To proof that the xs:include basically works give xmllint a try:

	xmllint --schema Main.xsd Sample.xml (Sample.xml does not validate as it missing required element D defined in Include.xsd)
	xmllint --schema A/Main.xsd Sample.xml (Sample.xml does not validate as it missing required element E defined in B/Include.xsd)

Both assertions show that the xs:include works as otherwise the missing elements wouldn't have been detected.

**Expected behavior**
I would expect no unresolved references in any case - the directory layout should not influence the resolution process.

**Library Version**
I used v1.2.13 of XsdParser.

**Additional context**

[Home.zip](https://github.com/xmlet/XsdParser/files/15129683/Home.zip)

**Comment by lcduarte** [comment]
Hello,

Thanks for using the library and for the issue!

I've identified the issue and deployed a new version, [1.2.14](https://github.com/xmlet/XsdParser/tree/xsdParser-1.2.14), with the fix. If you identify another issue let me know.

**Comment by hschildb** [comment]
Hi, thank you very much for providing the library and fixing the problem so quickly. I really appreciate it :-)
