### ISSUE TITLE
Order of XSD schema's is unreliable

### ISSUE THREAD

**Issue by SimonCockx** [xmlet/XsdParser#74]
**Describe the bug**
The order of `parser.getResultXsdSchemas()` is unreliable over different runs and different platforms, which is making some of my code produce output in an unreliable order. This is due to the underlying `HashMap` of `parseElements`:
```
    /**
     * A {@link List} which contains all the top elements parsed by this class.
     */
    public Map<String, List<ReferenceBase>> parseElements = new HashMap<>();
```
Note that the documentation is also out-of-date. It is not a list.

**Expected behavior**
I would like to iterate in the same order as the schema files were included, i.e., the main schema file first, followed by its first include (which can include schemas transitively), followed by its second include, etc.

Proposal: change `parseElements` to a `LinkedHashSet`, which respects insertion order:
```
public Map<String, List<ReferenceBase>> parseElements = new LinkedHashMap<>();
```
I can confirm that this would solve my issue.

**Library Version**
`1.2.17`

**Comment by lcduarte** [comment]
Hello,

Thanks for the issue and the suggestion, I've created a new version with it, [1.2.18](https://github.com/xmlet/XsdParser/tree/xsdParser-1.2.18).
