### ISSUE TITLE
Issue with substitutionGroup

### ISSUE THREAD

**Issue by Tim-W** [xmlet/XsdParser#9]
If there is an xs:element definition as follows:
```
<xs:element name="someThing" substitutionGroup="someCategory">
		<xs:complexType>
[...]
```
Then the call `element.getXsdComplexType` returns `null`.

What I expect is that the `element.getXsdComplexType` call returns the xs:complexType element, as happens when the substitutionGroup attribute is removed from the xs:element.

**Comment by lcduarte** [comment]
Hello Tim,
Thanks for pointing it out, it should be fixed in the new release I just made (1.0.19). 
Feel free to test again and let me now if it's all fine.

**Comment by Tim-W** [comment]
Yes, thank you :+1:

**Comment by fmcarvalho** [comment]
@Tim-W give a star please to the XsdParser repository!
